version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-container
    image: my-laravel-app:latest
    restart: always
    volumes:
      - app-data:/var/www/html  # Use a named volume instead of a bind mount
      - ./storage:/var/www/html/storage  # Ensures storage is persistent
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:  # Load environment variables from .env file
      - .env

  db:
    image: mysql:8.0  # Use a specific version for stability
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db-data:
  app-data:


