name: Build, Push, and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end  # 👈 Important: run commands inside frontend/
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-next-js-frontend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-next-js-frontend:latest ${{ secrets.DOCKER_USERNAME }}/my-next-js-frontend:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-next-js-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-next-js-frontend:${{ github.sha }}

  trigger-local-script:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: front-end
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set UTF-8 Encoding
        run: echo "Setting UTF-8 encoding..."

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Start Local Docker Registry
        run: docker run -d -p 5000:5000 --name registry registry:2    

      - name: Run Deployment Script
        run: python scripts/push_to_local_registry.py
